
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RSPAREN = 12;
  public static final int MULT = 28;
  public static final int EQUALS = 23;
  public static final int COMMENT = 40;
  public static final int LPAREN = 7;
  public static final int INT = 17;
  public static final int MINUS = 27;
  public static final int STATIC = 3;
  public static final int RPAREN = 8;
  public static final int NOT = 36;
  public static final int SEMICOLON = 16;
  public static final int AND = 24;
  public static final int LT = 25;
  public static final int COMMA = 30;
  public static final int CLASS = 13;
  public static final int PLUS = 26;
  public static final int MAIN = 5;
  public static final int IF = 19;
  public static final int THIS = 34;
  public static final int ID = 38;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 15;
  public static final int TRUE = 32;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int NUMBER = 37;
  public static final int VOID = 4;
  public static final int ELSE = 20;
  public static final int LCPAREN = 9;
  public static final int RCPAREN = 10;
  public static final int WHILE = 21;
  public static final int PUBLIC = 2;
  public static final int EXTENDS = 14;
  public static final int STRING = 6;
  public static final int FALSE = 33;
  public static final int INLINE_COMMENT = 39;
  public static final int LSPAREN = 11;
  public static final int PRINT = 22;
  public static final int LENGTH = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "LPAREN",
  "RPAREN",
  "LCPAREN",
  "RCPAREN",
  "LSPAREN",
  "RSPAREN",
  "CLASS",
  "EXTENDS",
  "RETURN",
  "SEMICOLON",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "PRINT",
  "EQUALS",
  "AND",
  "LT",
  "PLUS",
  "MINUS",
  "MULT",
  "DOT",
  "COMMA",
  "LENGTH",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "NOT",
  "NUMBER",
  "ID",
  "INLINE_COMMENT",
  "COMMENT"
  };
}

